name: p12_basic_widgets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+6

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  alarm: ^3.0.12
  ansicolor: ^2.0.2
  audioplayers: ^5.2.1
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.17
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.3
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_location_marker: ^8.0.5
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  latlong2: ^0.9.0
  location: ^5.0.3
  logger: ^2.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.3
  test: ^1.24.9
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
   uses-material-design: true
   assets: 
   - assets/images/
