name: p12_basic_widgets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_location_marker: ^8.0.5
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  latlong2: ^0.9.0
  location: ^5.0.3
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  test: ^1.24.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
   uses-material-design: true
   assets: 
   - assets/images/
