// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzS3zmzeqO4mFG3TDf2-KyFz7AS2Ok-R8',
    appId: '1:492160242371:web:4914d144c6d8f666b04876',
    messagingSenderId: '492160242371',
    projectId: 'for-helpers',
    authDomain: 'for-helpers.firebaseapp.com',
    storageBucket: 'for-helpers.appspot.com',
    measurementId: 'G-MZS1TFPXJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfSH5qGxnuAV1Gn5sTz7hd9DWVqBRbjks',
    appId: '1:492160242371:android:241eecb720695179b04876',
    messagingSenderId: '492160242371',
    projectId: 'for-helpers',
    storageBucket: 'for-helpers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoVbJi4dHq3YD9Y-pPM17mpZY5wouEOEw',
    appId: '1:492160242371:ios:1d57c8bf5ce5c658b04876',
    messagingSenderId: '492160242371',
    projectId: 'for-helpers',
    storageBucket: 'for-helpers.appspot.com',
    iosBundleId: 'com.example.p12BasicWidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoVbJi4dHq3YD9Y-pPM17mpZY5wouEOEw',
    appId: '1:492160242371:ios:6a0d2a652d6bfd69b04876',
    messagingSenderId: '492160242371',
    projectId: 'for-helpers',
    storageBucket: 'for-helpers.appspot.com',
    iosBundleId: 'com.example.p12BasicWidgets.RunnerTests',
  );
}
